### ISSUE TITLE
翻译插件建议

### ISSUE THREAD

**Issue by miniocean404** [saga7878/Translator#1]
1. 建议添加微软翻译，因为它支持国内的网络。
2. 希望可以和 webstorm 的 translation 插件的翻译类似，可以在翻译的时候自动把注释的标签 /**/ 或者 // 自动去除。

**Comment by tclxmeng-jia** [comment]
> 1. 建议添加微软翻译，因为它支持国内的网络。
> 2. 希望可以和 webstorm 的 translation 插件的翻译类似，可以在翻译的时候自动把注释的标签 /**/ 或者 // 自动去除。

1.  目前插件使用的就是微软翻译，你是在使用过程中遇到了网络问题吗？
2. 关于自动去除注释标记功能已经实现，请更新最新版本。

**Comment by saga7878** [comment]
> 1. 建议添加微软翻译，因为它支持国内的网络。
> 2. 希望可以和 webstorm 的 translation 插件的翻译类似，可以在翻译的时候自动把注释的标签 /**/ 或者 // 自动去除。

1. 目前插件使用的就是微软翻译，你是在使用过程中遇到了网络问题吗？
2. 关于自动去除注释标记功能已经实现，请更新最新版本。

**Comment by miniocean404** [comment]
感谢，我在插件文档看到的翻译语言是 google 和 deep 所以我才问这个问题
